FROM node:20-alpine

ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

WORKDIR /usr/src/app

COPY package*.json ./

RUN rm -rf node_modules/.vite
RUN npm install
COPY client/src/lib/queryClient.ts client/src/lib/queryClient.ts
COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev:client", "--host", "0.0.0.0"]