services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=kittypaw_user
      - POSTGRES_PASSWORD=kittypaw_password
      - POSTGRES_DB=kittypaw_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kittypaw_user -d kittypaw_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./apps/app_principal
      dockerfile: Dockerfile.backend
    ports:
      - '5000:5000'
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://kittypaw_user:kittypaw_password@db:5432/kittypaw_db?sslmode=disable

  frontend:
    build:
      context: ./apps/app_principal
      dockerfile: Dockerfile.frontend
    ports:
      - '5173:5173'
    depends_on:
      - backend

volumes:
  postgres_data:

networks:
  default:
    driver: bridge