version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      # Usamos el nuevo Dockerfile optimizado en la raíz
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    environment:
      # Asegura que el backend pueda encontrar la base de datos
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    # El comando ahora ejecuta la versión de producción pre-construida
    command: npm start --workspace=app_principal

volumes:
  postgres_data:
